### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Duxql**
Should be completely done
Should be running correctly
Should have the testing using Debug.Assert to make sure the values are within the expected outcome

### CODE REVIEW

**Review by LeoNaylor04 — APPROVED** [review]
Code functionality requirements have been met. The code is formatted into the correct classes and the uses of comments and appropriate variable names highly increases the readability. I do believe an error will be generated in the Die class where there is an attempt to output a string and an integer in the same line.

**Comment by DylanKrohnen** [comment]
- The requirements of the project have been met as the program successfully creates three random integers and outputs the sum of them to the user.
- The code follows the style guide and variables are given appropriate names.
- The code is easy to read and code comments have been included throughout.
- Error handling is included within the testing class however gave error _CS0029: Cannot implicitly convert type 'void' to 'int'_ when trying to run.

**Review by DylanKrohnen — APPROVED** [review]
- The requirements of the project have been met as the program successfully creates three random integers and outputs the sum of them to the user.
- The code follows the style guide and variables are given appropriate names.
- The code is easy to read and code comments have been included throughout.
- Error handling is included within the testing class however gave error _CS0029: Cannot implicitly convert type 'void' to 'int'_ when trying to run.

**Review by kam-s8 — COMMENTED** [review]
1. Have requirements been met? Yes requirements have been met and code works. No errors spotted.
2. Is the code formatted using the Style Guidelines correctly? Yes it is formatted correctly.
3. Is the code easy to read? The code is well written and commented making it easy to read and understand its intentions.
4. Are different errors handled correctly? Yes they are handled properly.

**Review by kam-s8 — APPROVED** [review]

**Pull request merged**
